# Generated by Django 4.0.1 on 2022-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombreCategoria', models.CharField(primary_key=True,max_length=50)),
            ],
        ),
    ]
