# Generated by Django 4.0.1 on 2022-05-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('idFlor', models.CharField(primary_key=True, serialize=False)),
                ('nombreFlor', models.CharField(max_length=20)),
                ('descFlor', models.CharField(max_length=50, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flower.categoria')),
            ],
        ),
    ]
